"""Added rule_number column

Revision ID: 86f82d60744a
Revises: 0acd1dfc89fb
Create Date: 2023-10-22 03:45:20.687853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "86f82d60744a"
down_revision: Union[str, None] = "0acd1dfc89fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules", sa.Column("rule_number", sa.String(), nullable=False)
    )
    op.create_unique_constraint("rule_number", "rules", ["rule_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("rule_number", "rules", type_="unique")
    op.drop_column("rules", "rule_number")
    # ### end Alembic commands ###
