"""empty message

Revision ID: 2e5359d8cb3b
Revises: 86f82d60744a
Create Date: 2024-01-22 02:47:20.750302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2e5359d8cb3b"
down_revision: Union[str, None] = "86f82d60744a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_unique_constraint("rule_number", ["rule_number"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("moderator_id", sa.Integer())
        )
        batch_op.create_unique_constraint("moderator_id", ["moderator_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("moderator_id")

    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_constraint("rule_number", type_="unique")

    # ### end Alembic commands ###
